#!/bin/bash
# This hook is run after every virtualenv is activated.

cd () {
    if (( $# == 0 )) && [[ -e $VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME ]]
    then
        cdproject
        else
        builtin cd "$@"
    fi
}


