#!/bin/bash
# This hook is run before every virtualenv is activated.

if [ -f $VIRTUAL_ENV/.modules ]
then
    for module in `cat $VIRTUAL_ENV/.modules`
    do
        module load $module
    done
fi
